### ISSUE TITLE
Requesting ability to detect if there is an authenticator available which is capable of resident key credential

### ISSUE THREAD

**Issue by sbweeden** [w3c/webauthn#987] opened 2018-07-09 00:55 UTC
As a relying-party developer, I would like to be able to detect (before sending a navigator.credentials.create request) if there is an authenticator available that can accept and act on the "requireResidentKey": true authenticatorSelection criteria.

The reason for this is that such an authenticator may be used to support username-less authentication and is in many scenarios more desirable than registering for just 2nd-factor purposes using a derived credential (since such a registration can also be used for step-up or 2nd factor authentication as well).

Without a discovery API to detect this (and potentially other properties of available authenticators), the RP must first try to register with requireResidentKey: true, and if that fails, fallback to 2nd-factor. This has undesirable user experience issues.

The isUserVerifyingPlatformAuthenticatorAvailable is close, but does not cater for portable keys that support requireResidentKey: true.

**Comment by akshayku** [comment] 2018-07-10 18:42
Not possible due to hot plugging nature of external authenticators. Closing this as by design.

**Comment by equalsJeffH** [comment] 2018-07-10 21:57
well, it would be at least possible for platform authenticators, and attached roaming/external authnrs?  Also, more full-featured authnr selection features are being collected for Level 2. reopening.

**Comment by akshayku** [comment] 2018-07-10 23:50
@equalsJeffH this is NOT for platfrom authenticators. This ask is for external authenticators which are always assumed to be hot-plugged. And that is why, I am closing this. I know Platform capabilities API ask but that is not what this issue is about. Please open platform capabilities API ask if you want that.

**Closed by akshayku** 2018-07-10 23:50 UTC
Labels: stat:breaking, type:technical

**Comment by equalsJeffH** [comment] 2019-03-07 18:39
at webauthn f2f 7-mar-2019, we agreed that this issue is "too big a hammer" for the described problem. However, some assert that issue #991 proposes a way to address the issue with a more appropriately sized hammer.
