### ISSUE TITLE
Base64 of fields to simplify javascript/json behaviour

### ISSUE THREAD

**Issue by Firstyear** [w3c/webauthn#1619] opened 2021-06-01 04:03 UTC
In the webauthn standard, a number of fields are defined as javascript structures that are sent to the navigator.credentials api's of the client. Some of these fields makes use of the type "BufferSource" which is a javascript Uint8Array. Notable examples are `PublicKeyCredentialCreationOptions.challenge`, `PublicKeyCredentialUserEntity.id`. 

While these may be javascript types, they are not themself able to convert directly from json to javascript - these actually on deserialisation from json create an array type that is not suitable for use where a uint8array is used. 

This has led to a number of implementations having to "work around this". The common workaround is the use of base64 (of various formats ...) such as on oktas sign in page, https://webauthn.io/ and others. Many of these ship their own base64 implementations, as javascript has no method to natively decode from base64 to a uint8array.

The primary concern is that this means that javascript for webauthn will likely be incompatible between backends and RP's, which could reduce the ability to share or adopt code.

The other concern is that this necessitates that client javascript *must* alter the content of the request options in order to proceed in calling the navigator.credentials api. It adds a needless extra hurdle for implementors to jump through, and presents a silent and subtle trap. 

I would suggest that the standard be extended so that fields have an `encoded` form of DOMString available. This DOMString must contain base64url encoded data, that the navigator.credentials api would decode. If the `encoded` form is not present, then the previous id/challenge fields are inspected.

```
dictionary PublicKeyCredentialRequestOptions {
   DOMString encodedChallenge;
   BufferSource                challenge;
   ...
}
```

This would allow implementors of site specific javascript to more easily handle the options that are provided from the server, and removes the need to alter and modify their content.

**Comment by MasterKale** [comment] 2021-06-01 04:37
That was something that always miffed me about the spec: it didn't seem very considerate of developers' time to not require clients to handle encoding to/decoding from Base64URL. [Entire](https://github.com/MasterKale/SimpleWebAuthn/tree/master/packages/browser) [libraries](https://github.com/github/webauthn-json) exist just to handle this song-and-dance especially because, as you said, browser JavaScript lacks native methods to encode/decode Base64URL. It's so much code that could be thrown away if data structures in the spec reflected the common use of JSON to send data between browser and RP in the web application context in which WebAuthn was written for. RPs have an easier time encoding to Base64URL, while browsers, as WebAuthn clients, are better-positioned to encode to Base64URL before returning from `navigator.credentials.create()`/`navigator.credentials.get()`.

I'd support efforts to consider such an either/or "`encoded`" option for things like `challenge`'s or credential `id`'s. I think it would reduce a lot of friction to adoption so developers can more easily incorporate this API into their application.

**Comment by emlun** [comment] 2021-06-01 06:18
Duplicate of #1362, which was closed with [this remark](https://github.com/w3c/webauthn/issues/1362#issuecomment-577405853):

> On the call of 2020-01-22 it was decided that the use of ArrayBuffers is reflecting W3C direction as we understand it and that revisiting that would be too much. [...]

So although I agree it's a bit cumbersome, the `encoded*` proposal will likely also be rejected with the above reasoning.

However, #1362 did lead to issue #1363 and PR #1395 which added the [`getPublicKey()`](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-authenticatorattestationresponse-getpublickey) method. It might be worth (re)considering if it could be worthwhile to add some methods like `PublicKeyCredential.fromJsonWithBase64Url(DOMString)` and `.toJsonWithBase64Url()`.

**Comment by emlun** [comment] 2021-06-30 19:25
On 2021-06-30 WG call: Closing this as duplicate of #1362 and due to inactivity. We might consider adding methods similar to `getPublicKey()` if someone is willing to push for it, but we're not currently seeing that.

**Closed by emlun** 2021-06-30 19:25 UTC
