### ISSUE TITLE
Key types and algorithms are confusing

### ISSUE THREAD

**Issue by balfanz** [w3c/webauthn#547] opened 2017-09-08 16:45 UTC
We use the [CoseAlgorithmIdentifier](https://github.com/w3c/webauthn/blob/14c2733ca6a4a9568e4c48fef1b870448818e811/index.bs#L1449) throughout the doc for different purposes: sometimes to denote a type of key, sometimes to denote a signature algorithm.

For example, when [describing an attestation statement](https://github.com/w3c/webauthn/blob/14c2733ca6a4a9568e4c48fef1b870448818e811/index.bs#L2317), we use it to describe the algorithm used to generate the attestation signature. When generating new keys, we use it to [specify the type of keys](https://github.com/w3c/webauthn/blob/14c2733ca6a4a9568e4c48fef1b870448818e811/index.bs#L1082) the caller wants to generate.

There are two problems with the latter use of CoseAlgorithmIdentifier:

1. It appears to limit the use of a key to a specific signature algorithm. We shouldn't do that.

2. It underspecifies the key, for example by not mentioning the elliptic curve being used, or the size of the RSA exponent. 

We should fix this. Let's mention key types where key types are required, and signature algorithms where signature algorithms are required. I would also recommend that we use web-friendly nomenclature in parameters (i.e., [JWA names](https://tools.ietf.org/html/rfc7518)), and COSE-based "names" (integers) only in binary encodings (like attestation statements, authenticator data, etc.)

**Comment by ve7jtb** [comment] 2017-09-08 17:07
I agree in general, however limiting a key to a particular signature alg is a goo thing in theory as it protects against some theoretical attacks against the private key.   The current wording however is probably not the best way to make that clear.

**Comment by selfissued** [comment] 2017-09-28 02:46
I agree with John that limiting a key to use with a particular algorithm is a good security practice.  This was intentional.

I don't know why you're saying that the curve is not specified.  The COSE algorithm identifiers are specific to particular algorithms, including the curve.  For instance, the ES256 (-7) is specific to a particular curve.

**Comment by jcjones** [comment] 2017-10-04 17:59
I agree with limiting keys to specific algorithms; this is commonplace throughout other specs.

And if some curves are under-specified, then that sounds like a COSE issue?

**Comment by nadalin** [comment] 2017-10-10 20:59
@selfissued where do we stand on this issue ?

**Comment by selfissued** [comment] 2017-10-10 22:50
I believe this should be closed as "won't fix" since the premise of the issue is false.  The curves for all COSE algorithms are fully specified.

**Closed** 2017-10-11 18:55 UTC
Labels: priority:implementation, stat:breaking, subtype:algorithms/WebIDL
