### ISSUE TITLE
Using a smart phone as an authenticator with WebAuthn

### ISSUE THREAD

**Issue by maranjavatraining** [w3c/webauthn#1046] opened 2018-08-26 19:14 UTC
I am wondering is there any way to use a smart phone as an authenticator through WebAuthn, when the web application is running on a laptop/desktop? if yes, could you please illustrate how can I test it.OR, Is there any live demo for that?
any comments accepted 
Thanks

**Comment by equalsJeffH** [comment] 2018-08-27 18:30
@maranjavatraining --
> I am wondering is there any way to use a smart phone as an authenticator through WebAuthn...

Yes, see https://fidoalliance.org/fido-alliance-and-w3c-achieve-major-standards-milestone-in-global-effort-towards-simpler-stronger-authentication-on-the-web/ and note the reference to CTAP:

> ...  FIDO’s Client to Authenticator Protocol (CTAP) specification. CTAP enables an external authenticator, such as a security key or a mobile phone, to communicate strong authentication credentials locally over USB, Bluetooth or NFC to the user’s internet access device (PC or mobile phone).

The most recent publicly-available CTAP spec is here: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-client-to-authenticator-protocol-v2.0-rd-20180702.html

see also: 
* https://cloudblogs.microsoft.com/enterprisemobility/2018/04/12/big-news-in-our-drive-to-eliminate-passwords-fido2-webauthn-reaches-candidate-recommendation-status/
* https://www.aboutchromebooks.com/news/chrome-os-and-chrome-getting-support-for-biometric-2fa-with-ctap2-standard/
* [Intent to Ship: WebAuthentication API](https://groups.google.com/a/chromium.org/d/msg/Blink-dev/o9RU6Vv0xeM/EGnQOExbAAAJ)

**Comment by emlun** [comment] 2018-08-29 16:56
This looks like a duplicate of #954.

**Comment by jcjones** [comment] 2018-08-29 17:42
Agreed, is a dupe of #954.

**Closed by jcjones** 2018-08-29 17:42 UTC

**Comment by mehakzahra1** [comment] 2019-11-04 15:38
Guys any body have a news regarding BLE falgs in chrome. Is it mandatory to enable BLE flags on chrome to use webauthn for this specific usecase?
Is ther any alternative approach?

**Comment by mehakzahra1** [comment] 2019-11-04 15:47
Guys anybody have news regarding BLE flags in chrome. Is it mandatory to enable BLE flags on chrome to use webauthn for this specific usecase?
Is ther any alternative approach?
