### ISSUE TITLE
Attestation for DPK(device-bound public key)

### ISSUE THREAD

**Issue by keikoit** [w3c/webauthn#1798] opened 2022-09-10 00:04 UTC
After discussing with various RPs on DPK (device-bound public key), we are agreeing that those RPs who want to use a DPK need attestation for a DPK and the attestation must be protected from replay attacks. 
I am wondering if this requirement is specified in the specification already? 
Without replay attack protection, a DPK is equivalent to a bearer token and RPs cannot trust  it.

Related Issue: https://github.com/w3c/webauthn/issues/1799

**Comment by timcappalli** [comment] 2022-09-11 17:23
Duplicate of #1799

**Closed by timcappalli** 2022-09-11 17:23 UTC
Labels: stat:Discuss, subtype:FeatureProposal
