### ISSUE TITLE
Decoding TPM `certInfo` and `pubArea`?

### ISSUE THREAD

**Issue by subyraman** [w3c/webauthn#984] opened 2018-07-04 15:24 UTC
Hello! In exploring Windows Hello with WebAuthn I find myself stuck at the verification procedure for the TPM attestation statement. The spec tells me to verify members of `certInfo` and `pubArea` but from reading I'm not entirely certain how to perform the correct decode on the bytes provided. The TPM spec linked is pretty difficult to parse and wasn't helpful either in terms of helping me decode the data provided.

Assuming I haven't missed the correct instructions in the spec, is this something that could be added?

**Comment by emlun** [comment] 2018-07-04 15:36
Hi! This looks like a duplicate of PR #966 and issues #929 and #950. We agree that the linked spec is not fun to read, but I think we're leaning toward that not duplicating instructions from it (and risking getting them wrong) seems like a lesser evil.

**Comment by subyraman** [comment] 2018-07-04 15:53
Cheers! I looked over the linked PR/issues and I don't know if they address the issue about how to go about decoding the `certInfo` and `pubInfo`? I did do my best to read the TPM spec but (afaict) the linked section describes the object shape and not how to go about decoding it in an RP-type situation.

**Comment by herrjemand** [comment] 2018-07-04 18:48
![image](https://user-images.githubusercontent.com/1636116/42291393-384d8cb6-7fc3-11e8-927e-9f7dbb26ba4b.png)

**Comment by herrjemand** [comment] 2018-07-04 18:48
![image 1](https://user-images.githubusercontent.com/1636116/42291398-44a35306-7fc3-11e8-96f9-d4661b618a9d.png)

**Comment by herrjemand** [comment] 2018-07-04 18:51
Courtesy of @apowers313 *)

**Comment by apowers313** [comment] 2018-07-05 17:22
Here's some sample code too:

https://github.com/apowers313/fido2-lib/blob/master/lib/attestations/tpm.js

Drop me a line if you need any help.

**Comment by nadalin** [comment] 2018-07-05 19:11
Closing this issue as we should not duplicate information

**Closed by nadalin** 2018-07-05 19:11 UTC

**Comment by subyraman** [comment] 2018-07-05 19:22
I don't think this should be closed; this isn't a duplicate issue and there isn't a good resource referenced in the spec about how to properly work with the attestation data provided.
