### ISSUE TITLE
Define how to verify the attestation certificate

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#605] opened 2017-10-04 03:23 UTC
https://w3c.github.io/webauthn/#registering-a-new-credential says
> Use the X.509 certificates returned by the verification procedure to verify that the attestation public key correctly chains up to an acceptable root certificate.

@sahf says that leaves a bunch of questions unanswered:

1. Should the RP honor the validity dates in the attestation certificate? If so, how should the user be told that his token is too old to be used?
1. Should the RP honor the "critical" bit for X.509 extensions, meaning that it should refuse to register in the case where a token sends a critical extension that is not understood?
1. May a token return a chain consisting of multiple certificates, and if so, may the RP build a different chain than the one that was supplied?
1. May/should the RP consult any of the standard revocation mechanisms specified in the certificate, such as a CRL or OCSP responder?
1. …

We might be able to start by referring to https://tools.ietf.org/html/rfc5280#section-6, but I think that still leaves a bunch of the above questions open, and isn't the most helpful format for RPs trying to write an implementation.

I've marked this low priority because we may want to discourage RPs from checking certificate validity at all (#576), in which case most of them won't care about the details of how to check the certificate.

**Comment by SAHF** [comment] 2017-10-05 00:32
For context: I know little about WebAuthn & my comments were pretty off-the-cuff.  My concern was that chain building in HTTPS is a (very) complex topic & that without specific guidance, WebAuthn implementors may reuse features of HTTPS implementations—maybe even inadvertently!

So if you intend the verification procedure here to be simpler than what it is in HTTPS, it is probably worth writing out the procedure in detail, and/or specifically proscribing HTTPS features that you intend to avoid (such as critical extensions).

**Comment by arshadnoor** [comment] 2017-10-15 22:42
X.509 certificate-chain validation was designed to help Relying Parties (RP) in the Public Key Infrastructure-space to determine whether the end-entity certificate presented to them in the transaction presents an acceptable risk.  That this is an arduous process that has very few implementations in the business world - and virtually, none, in the consumer-space - is a reflection of the complexity and challenges in working with digital certificates.  The RP's risk still remains regardless of whether the authentication scheme is TLS-ClientAuth or FIDO.

The Attestation certificate in a FIDO Registration is intended to provide the RP a fair amount of information on whether the FIDO public-key being presented in the transaction is an acceptable risk.  If the RP does **not** perform adequate certificate-chain validation to determine that risk, then the logical conclusion one may draw from this is that either the RP does **not** engage in business transactions that present much risk to the RP (perhaps a web-page to sign-up for volunteer efforts at the local Parent Teacher's Association) and merely wants to eliminate the hassle of having a password database - or the RP is ignorant of the risk of ignoring the Attestation Certificate (AC).  This, of course, assumes that the manufacturer of the FIDO Authenticator knew what they were doing when they created the Attestation Certificate and its chain (and are also following up on doing the right thing in providing information to the world on their certification policy/practices, and revocation status of the AC).

IMO, there is no reason for the FIDO Alliance or the W3C to provide any more information on how to perform cert-chain validation, and how to make risk-decisions based on such validation - there is more than enough information published on this topic, including open-source code on how to perform PKIX-validation.    Discouraging RPs from performing adequate cert-chain validation is equivalent to discouraging them to obey traffic lights at an intersection.

If an RP is knowledgeable about public-key cryptography, digital certificates and cert-chain validation, then they have a basis to avoid a failure in their implementation of the protocol; otherwise, to dive into FIDO with little knowledge about their responsibilities, is to merely replace a password-based breach with a FIDO-based breach in due course.

Arshad Noor
StrongAuth, Inc.

**Comment by nadalin** [comment] 2017-10-16 13:14
@jyasskin  Why do we need to worry about this as the RP can verify how every they want this is out of scope of WebAuthn WG, I suggest we close this no action

**Comment by AngeloKai** [comment] 2017-10-25 18:32
Agreed. Closing with no action.

**Comment by AngeloKai** [comment] 2017-10-25 18:33
Given that this is just description of what RP needs to do instead of how platform implements the feature, set the issue to PR. 

@equalsJeffH @nadalin @YubicoDemo for tracking.

**Closed by AngeloKai** 2017-10-25 18:32 UTC
Labels: priority:low
