### ISSUE TITLE
7.2. Verifying an Authentication Assertion is missing steps 7 and 8 

### ISSUE THREAD

**Issue by arianvp** [w3c/webauthn#2049] opened 2024-03-25 13:17 UTC
## Proposed Change

It skips from step 6 to step 9. I assume  some steps were removed when rewording things from "Credential Source" to "Credential Record"

**Comment by emlun** [comment] 2024-03-25 13:24
Thanks, this is a known issue. Duplicate of #1913.

**Closed by emlun** 2024-03-25 13:24 UTC
Labels: type:technical
