### ISSUE TITLE
WebAuthn Client

### ISSUE THREAD

**Issue by pkuntal** [w3c/webauthn#927] opened 2018-06-01 11:27 UTC
Is WebAuthn Client nothing but a browser or it can be implemented as a separate app?is it a user agent which interacts with authenticator? and should be implemented to route all FIDO authentication request via authenticator?

**Comment by emlun** [comment] 2018-06-01 13:15
This looks like a duplicate of #928.

**Closed by emlun** 2018-06-01 13:15 UTC
