### ISSUE TITLE
Support WWW-Authenticate (for one request. can be upgraded to cookies if necessary.)

### ISSUE THREAD

**Issue by SoniEx2** [w3c/webauthn#1616] opened 2021-05-25 14:13 UTC
It would be useful to be able to use WebAuthn with WWW-Authenticate. Obviously it would only grant access for one request, but that's enough for setting a long-term session cookie.

**Comment by emlun** [comment] 2021-05-25 19:52
This would seem to overlap significantly with #1255. See in particular https://github.com/w3c/webauthn/issues/1255#issuecomment-559248437 :+1: 

>[...] perhaps the "pluggable authn mechs" being discussed in the QUIC IETF WG are potentially a means to ultimately address the anticipated use cases here?

Might we close this as a duplicate of #1255?

**Comment by SoniEx2** [comment] 2021-05-25 19:58
Uh isn't that just for QUIC (transport protocol)? That doesn't seem relevant to WWW-Authenticate, and while there is some overlap with #1255, nobody actually wants to use WWW-Authenticate as part of their auth flow because the UX for it is pretty bad for *general* web use.

**Comment by emlun** [comment] 2021-05-25 20:29
I'll admit I don't really know what QUIC is or how it works. At the time I got the impression that its "pluggable authn mechs" are something like an analogue of WWW-Authenticate and similar, but implemented in the transport layer instead of the HTTP layer.

But is your use case to support user clients other than web browsers? In that case, there's already nothing stopping servers from supporting that. See for example the [Okta WebAuthn authentication API](https://developer.okta.com/docs/reference/api/authn/#verify-webauthn-factor). There's no cross-RP standardized API for this though, if that's what you're asking for.

**Comment by SoniEx2** [comment] 2021-05-25 20:43
It could still be used with browsers, but it'd be primarily to *protect resources* (as WWW-Authenticate is intended to be used), instead of providing form-based or form-equivalent user authentication (which is often more about personalization, or as it's commonly referred to nowadays, targeting).

**Comment by ignaloidas** [comment] 2021-06-02 13:11
Using WWW-Authenticate could be a solution for #1255, though it would remove styling opportunities, but if I understand correctly it would be easier to do from browser point of view since now no new HTML semantics would be added. But I'm not sure how you would handle registration in this way, as WWW-Authenticate isn't fit for that.

**Comment by SoniEx2** [comment] 2021-06-02 13:20
It's not intended for registration. Registration is meant to be done out of band. (Well, in the context of WWW-Authenticate at least - webforms count as out-of-band for that.)

To be honest it would be nice to remove styling opportunities in favour of anti-phishing design, but this isn't that. That can be addressed some other way.

**Comment by equalsJeffH** [comment] 2021-06-02 18:45
> It would be useful to be able to use WebAuthn with WWW-Authenticate

Sure, ISTM IIUC that this is _nominally_ possible to achieve since the "Access Authentication Framework" that the `WWW-Authenticate` response header field is a part of is challenge-response.  `WWW-Authenticate` conveys an "authentication scheme" identifier and a challenge:
>  `WWW-Authenticate = 1#challenge`  // [[RFC7235 S 4.1](https://datatracker.ietf.org/doc/html/rfc7235#section-4.1)]
> `challenge   = auth-scheme [ 1*SP ( token68 / #auth-param ) ]` //  [RFC7235 S 2.1](https://datatracker.ietf.org/doc/html/rfc7235#section-2.1)

One could spec this by defining a new `auth-scheme` (say "webauthn1") and how the server's params are mapped into `( token68 / #auth-param )`,  how the client deciphers all that into `nav.creds.get()` call params, and then maps the results into a `Authorization` request header field's `credentials` component:
> `Authorization = credentials`

..and then how the server parses and verifies it upon receipt.

However, ISTM we would not spec this in the webauthn spec or the W3C, but rather if someone really feels it's worth the effort to do so, I'd suggest doing it in the IETF as an Internet-Draft to begin with (one'd figure out there in the IETF whether it'll end up on the standards track or informational or experimental or whatever).

**Comment by equalsJeffH** [comment] 2021-06-16 17:40
Closing this since it's not something we'd spec in the webauthn working group.

**Closed by equalsJeffH** 2021-06-16 17:40 UTC
Labels: type:technical
