### ISSUE TITLE
PING suggest referencing the FIDO 100k batch requirements

### ISSUE THREAD

**Issue by agl** [w3c/webauthn#749] opened 2018-01-17 16:58 UTC
During the PING conference call of 2018-01-11, PING suggested that we reference the FIDO batch requirements.

**Comment by equalsJeffH** [comment] 2018-01-17 18:06
s/batch requirements/privacy principles/ ?  if so then is this a duplicate of issue #742 ?

**Comment by agl** [comment] 2018-01-17 18:13
We can obviously decide whether we actually want to do this, but the request that I noted down from the phone call was to reference the batch requirements for attestation certificates specifically. The FIDO Privacy Principles document doesn't seem to contain that.

**Comment by nadalin** [comment] 2018-01-18 16:40
@agl I think there is no harm as long as this is guidance, and this is not a duplicate of #472 so I think we should just do this

**Comment by selfissued** [comment] 2018-01-26 06:10
@agl where do you want this reference to be and what do you want it to say?  I'll create a PR to add it if I know what to write.

**Closed** 2018-01-26 23:05 UTC
Labels: subtype:privacy-cons, type:editorial
