### ISSUE TITLE
Revise same-origin as ancestor requirements

### ISSUE THREAD

**Issue by apowers313** [w3c/webauthn#1001] opened 2018-07-18 00:12 UTC
Picking up where we left off on w3c/webappsec-credential-management#3 and related to #873 and #911...

There is a need by some relying parties to be able to use WebAuthn in child browsing contexts (e.g. - iframes, child windows, etc.). Currently WebAuthn [requires](https://w3c.github.io/webauthn/#getAssertion) `sameOriginWithAncestors` which prevents these use cases.

@equalsJeffH had put together an [initial proposal](https://docs.google.com/presentation/d/1sK9hhI0y25iioyLGMKwdhtpe-sVRV7Ln4pMHR2JXApw/edit) on how this might work and presented it during a meeting and we didn't hear anyone complain.

**Comment by apowers313** [comment] 2018-07-18 17:54
Not putting this in the spec until L2 means that certain relying party use cases (which seem to be important for adoption) won't be implementable for at least a year.

Any chance we could do this for L1?

**Comment by ve7jtb** [comment] 2018-07-18 18:17
Talking to Jeff, there are WebAppSec dependencies to get this to work securely.

While I think we all want this to work,  just removing the restriction in WebAutn is not sufficient to have it work securely.   


We should try to sort this out so that at least not block it working once the other parts come together.  That, however, may be difficult to capture in spec language.

**Comment by mikewest** [comment] 2018-07-18 18:30
@equalsJeffH: What are the WebAppSec dependencies? Can y'all not just accept `sameOriginWithAncestors == false`?

**Comment by rlin1** [comment] 2018-10-22 14:47
We might want to add a note to the security considerations to point to intersection observer 2 (io2).

**Comment by rlin1** [comment] 2018-10-22 14:49
See also #969

**Comment by jcjones** [comment] 2018-10-22 14:52
> We might want to add a note to the security considerations to point to intersection observer 2 (io2).

Opened https://github.com/w3c/webauthn/issues/1105

**Comment by jcjones** [comment] 2018-10-22 14:54
This is now considered to be effectively a duplicate of #911, which all parties agreed to implement in Level 2, so closing this in favor of #911.

**Closed by jcjones** 2018-10-22 14:54 UTC
Labels: type:technical
